# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DJ Adams ðŸ‡ªðŸ‡º
email: qmacro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DJ's Weblog. Reserving the right to be wrong.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qmacro.org" # the base hostname & protocol for your site
twitter_username: qmacro
github_username:  qmacro
author: DJ Adams
title_image: /content/images/DJA-head.png

# Build settings
markdown: kramdown

theme: minima

google_analytics: UA-17535311-5
permalink: /:year/:month/:day/:title/
